### ISSUE TITLE
Demo `[−∞,3]` fails with empty error message

### ISSUE THREAD

**Issue by berrymot** [MurrayIII/UnicodeMathML#5]
![image](https://github.com/MurrayIII/UnicodeMathML/assets/50974538/1a733ad8-140a-4535-8025-d0c0fece2844)

**Comment by MurrayIII** [comment]
I no longer repro this

**Comment by berrymot** [comment]
I still do

**Comment by MurrayIII** [comment]
Curious. I get
![image](https://github.com/user-attachments/assets/f3fbfeff-8a49-4ca8-85e7-3266d2bf5e8a)

**Comment by berrymot** [comment]
![image](https://github.com/user-attachments/assets/9120f9bf-29da-479c-a124-59063998931e)

if i put any number of spaces after the comma it works fine

**Comment by MurrayIII** [comment]
If you turn on configuration option "emit default intents", it works. I uploaded a fix so that it works if this option is disabled. Thanks for spotting this.
