### ISSUE TITLE
Spelling of ½ is wrong

### ISSUE THREAD

**Issue by tom-huntington** [MurrayIII/UnicodeMathML#7]
If you hover over 𝜃 you get shown the TeX spelling `\theta`

However, if you type `1/2` it get's swapped with ½ but when you hover over it it shows `\u00BD`.

It seems like composite symbols may be not working properly.

How I wanted to use it, is by clicking on the examples. Then hovering to see the spelling that produces that symbols that make it up.

**Comment by tom-huntington** [comment]
Same again with ℝ.
It would be nice if it told me that the spelling was `\BbbR`

**Comment by MurrayIII** [comment]
"Spellings" like \u00BD are the Unicode code points. HTML has alphabetic names for a few of them, such as "half" for ½, so I'm adding them to the autocorrect list and character titles.

**Comment by MurrayIII** [comment]
Added control-word (LaTeX-like) entries for math alphanumerics and many other symbols.
